family: "${API_ECS_TASK}"
networkMode: awsvpc
cpu: "${API_ECS_CPU_UNITS}"
memory: "${API_ECS_MEMORY_UNITS}"
executionRoleArn: "${API_ROLE_ARN}"
taskRoleArn: "${API_ROLE_ARN}"
requiresCompatibilities:
  - FARGATE
volumes:
  - name: data
    efsVolumeConfiguration:
      fileSystemId: "${EFS_FILESYSTEM_ID}"
      authorizationConfig:
        accessPointId: "${EFS_ACCESS_POINT_ID}"
        iam: ENABLED
      transitEncryption: ENABLED
containerDefinitions:
  - name: logs
    image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
    firelensConfiguration:
      type: fluentbit
      options:
        enable-ecs-log-metadata: "true"
    memoryReservation: 50
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: "/analysistools/${TIER}/${APP}/api"
        awslogs-region: "${AWS_REGION}"
        awslogs-stream-prefix: logs

  - name: api
    image: "${BACKEND_IMAGE_LATEST}"
    portMappings:
      - protocol: tcp
        containerPort: 80
      - protocol: tcp
        containerPort: 8080
    environment:
      - name: ENV
        value: "${TIER}"
      - name: TZ
        value: "${TZ}"
      - name: DD_ENV
        value: "${TIER}"
      - name: DD_SERVICE
        value: "${TIER}-${APP}-api"
      - name: DD_VERSION
        value: "${APP_GIT_TAG}"
    secrets:
      - name: BASE_URL
        valueFrom: "/analysistools/${TIER}/${APP}/web/base_url"
      - name: LOG_LEVEL
        valueFrom: "/analysistools/${TIER}/${APP}/log_level"
      - name: NUM_SUBPROCESSES
        valueFrom: "/analysistools/${TIER}/${APP}/num_subprocesses"
      - name: DBSNP_VERSION
        valueFrom: "/analysistools/${TIER}/${APP}/dbsnp_version"
      - name: S3_BUCKET
        valueFrom: "/analysistools/${TIER}/${APP}/s3_bucket"
      - name: S3_BUCKET_DATA_DIR
        valueFrom: "/analysistools/${TIER}/${APP}/s3_bucket_data_dir"
      - name: DATA_DIR
        valueFrom: "/analysistools/${TIER}/${APP}/data_dir"
      - name: TMP_DIR
        valueFrom: "/analysistools/${TIER}/${APP}/tmp_dir"
      - name: LDASSOC_EXAMPLE_DIR
        valueFrom: "/analysistools/${TIER}/${APP}/ldassoc_example_dir"
      - name: POPULATION_SAMPLES_DIR
        valueFrom: "/analysistools/${TIER}/${APP}/population_samples_dir"
      - name: GENOTYPES_DIR
        valueFrom: "/analysistools/${TIER}/${APP}/genotypes_dir"
      - name: LDTRAIT_SRC
        valueFrom: "/analysistools/${TIER}/${APP}/ldtrait_src"
      - name: MONGODB_HOST
        valueFrom: "/analysistools/${TIER}/${APP}/mongodb_host"
      - name: MONGODB_PORT
        valueFrom: "/analysistools/${TIER}/${APP}/mongodb_port"
      - name: MONGODB_DATABASE
        valueFrom: "/analysistools/${TIER}/${APP}/mongodb_database"
      - name: MONGODB_USERNAME
        valueFrom: "/analysistools/${TIER}/${APP}/mongodb_username"
      - name: MONGODB_PASSWORD
        valueFrom: "/analysistools/${TIER}/${APP}/mongodb_password"
      - name: REQUIRE_TOKEN
        valueFrom: "/analysistools/${TIER}/${APP}/require_token"
      - name: TOKEN_EXPIRATION
        valueFrom: "/analysistools/${TIER}/${APP}/token_expiration"
      - name: TOKEN_EXPIRATION_DAYS
        valueFrom: "/analysistools/${TIER}/${APP}/token_expiration_days"
      - name: TOKEN_LOCK_TIMEOUT
        valueFrom: "/analysistools/${TIER}/${APP}/token_lock_timeout"
      - name: RESTRICT_CONCURRENCY
        valueFrom: "/analysistools/${TIER}/${APP}/restrict_concurrency"
      - name: LDLINK_INTERNAL_AUTH_TOKEN
        valueFrom: "/analysistools/${TIER}/${APP}/ldlink_internal_auth_token"
      - name: EMAIL_SMTP_HOST
        valueFrom: "/analysistools/${TIER}/${APP}/email_smtp_host"
      - name: EMAIL_ADMIN
        valueFrom: "/analysistools/${TIER}/${APP}/email_admin"
      - name: EMAIL_SUPERUSER
        valueFrom: "/analysistools/${TIER}/${APP}/email_superuser"
    mountPoints:
      - sourceVolume: data
        containerPath: "/data"
        readOnly: false
    logConfiguration:
      logDriver: awsfirelens
      options:
        Name: datadog
        tls: "on"
        tls.verify: "off"
        dd_service: "${TIER}-${APP}-api"
        dd_source: "httpd"
        dd_tags: "project:${APP},tier:${TIER},env:${TIER}"
        provider: ecs
      secretOptions:
        - name: Host
          valueFrom: "/analysistools/${TIER}/datadog/log_endpoint_host"
        - name: apikey
          valueFrom: "/analysistools/${TIER}/datadog/api_key"
    dockerLabels:
      com.datadoghq.tags.env: "${TIER}"
      com.datadoghq.tags.service: "${TIER}-${APP}-api"
      com.datadoghq.tags.version: "${APP_GIT_TAG}"
      com.datadoghq.ad.logs: '[{"source": "httpd", "service": "${TIER}-${APP}-api"}]'


  - name: datadog
    image: "public.ecr.aws/datadog/agent:latest"
    essential: true
    cpu: 256
    memory: 512
    portMappings:
      - protocol: tcp
        containerPort: 8126
    environment:
      - name: TZ
        value: "${TZ}"
      - name: DD_HOSTNAME
        value: default
      - name: DD_TAGS
        value: "team:analysis-tools project:${APP} tier:${TIER}"
      - name: DD_SITE
        value: ddog-gov.com
      - name: DD_LOGS_ENABLED
        value: "true"
      - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
        value: "true"
      - name: ECS_FARGATE
        value: "true"
      - name: DD_APM_ENABLED
        value: "true"
      - name: DD_APM_NON_LOCAL_TRAFFIC
        value: "true"
    secrets:
      - name: DD_API_KEY
        valueFrom: "/analysistools/${TIER}/datadog/api_key"
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: "/analysistools/${TIER}/${APP}/api"
        awslogs-region: "${AWS_REGION}"
        awslogs-stream-prefix: datadog-agent

tags:
  - key: Project
    value: "${APP}"
  - key: ApplicationName
    value: "${APP}"
  - key: ResourceName
    value: "${TIER}-${APP}-api-ecs-task"
  - key: ResourceFunction
    value: compute
  - key: EnvironmentTier
    value: "${ENVIRONMENT_TIER}"
  - key: Creator
    value: CF
