export const PLATFORM_LOOKUP: Record<string, string> = {
  // Affymetrix platforms
  "Affymetrix 10K Mapping": "A_10X",
  "Affymetrix Mapping 250K Nsp": "A_250N",
  "Affymetrix Mapping 250K Sty": "A_250S",
  "Affymetrix 50K Hind": "A_50H",
  "Affymetrix 50K Xba": "A_50X",
  "Affymetrix Axiom GW AFR": "A_AFR",
  "Affymetrix Axiom GW ASI": "A_ASI",
  "Affymetrix Axiom GW CHB2": "A_CHB2",
  "Affymetrix DMET Plus": "A_DMETplus",
  "Affymetrix Axiom GW EAS": "A_EAS",
  "Affymetrix Axiom GW EUR": "A_EUR",
  "Affymetrix Axiom Exome 1A": "A_Exome1A",
  "Affymetrix Axiom Exome 319": "A_Exome319",
  "Affymetrix Axiom GW Hu": "A_Hu",
  "Affymetrix Axiom GW Hu-CHB": "A_Hu-CHB",
  "Affymetrix Axiom GW LAT": "A_LAT",
  "Affymetrix OncoScan": "A_Onco",
  "Affymetrix OncoScan CNV": "A_OncoCNV",
  "Affymetrix Axiom Precision Medicine Research": "A_PMRA",
  "Affymetrix Axiom Precision Medicine Research Array": "A_PMRA",
  "Affymetrix SNP 5.0": "A_SNP5.0",
  "Affymetrix SNP 6.0": "A_SNP6.0",
  "Affymetrix Axiom UK Biobank": "A_UKBA",
  "Affymetrix Axiom UK Biobank Array": "A_UKBA",
  
  // Illumina platforms
  "Illumina Infinium Human100kv1": "I_100",
  "Illumina Human1Mv1": "I_1M",
  "Illumina Human1M-Duov3": "I_1M-D",
  "Illumina HumanHap240S": "I_240S",
  "Illumina HumanHap300v1": "I_300",
  "Illumina HumanHap300-Duov2": "I_300-D",
  "Illumina HumanHap550v1": "I_550v1",
  "Illumina HumanHap550v3": "I_550v3",
  "Illumina Human610-Quadv1": "I_610-Q",
  "Illumina Human650Y": "I_650Y",
  "Illumina Human660W-Quadv1": "I_660W-Q",
  "Illumina HumanCNV-12": "I_CNV-12",
  "Illumina HumanCNV370-Duov1": "I_CNV370-D",
  "Illumina HumanCNV370-Quadv3": "I_CNV370-Q",
  "Illumina HumanCVDv1": "I_CVD",
  "Illumina Cardio-MetaboChip": "I_CardioMetab",
  "Illumina HumanCore-12v1": "I_Core-12",
  "Illumina HumanCoreExome-12v1": "I_CoreE-12v1",
  "Illumina HumanCoreExome-12v1.1": "I_CoreE-12v1.1",
  "Illumina HumanCoreExome-24v1": "I_CoreE-24v1",
  "Illumina HumanCoreExome-24v1.1": "I_CoreE-24v1.1",
  "Illumina HumanCytoSNP-12v2": "I_Cyto-12v2",
  "Illumina HumanCytoSNP-12v2.1": "I_Cyto-12v2.1",
  "Illumina HumanCytoSNP-12v2.1 FFPE": "I_Cyto-12v2.1f",
  "Illumina Infinium CytoSNP-850K": "I_Cyto850",
  "Illumina HumanExome-12v1.1": "I_Exome-12",
  "Illumina HumanExon510Sv1": "I_Exon510S",
  "Illumina Global Diversity Array_Confluence": "I_GDA-C",
  "Illumina Global Screening version 1": "I_GSA-v1",
  "Illumina Global Screening version 2": "I_GSA-v2",
  "Illumina Global Screening version 3_Confluence": "I_GSA-v3C",
  "Illumina HumanImmuno-24v1": "I_Immuno-24v1",
  "Illumina HumanImmuno-24v2": "I_Immuno-24v2",
  "Illumina HumanLinkage-12": "I_Linkage-12",
  "Illumina HumanLinkage-24": "I_Linkage-24",
  "Illumina Infinium Multi-Ethnic Global-8": "I_ME-Global-8",
  "Illumina Multi-Ethnic Global": "I_MEGA",
  "Illumina Multi-Ethnic Global Array": "I_MEGA",
  "Illumina HumanNS-12": "I_NS-12",
  "Illumina HumanOmni1-Quadv1": "I_O1-Q",
  "Illumina HumanOmni1S-8v1": "I_O1S-8",
  "Illumina HumanOmni2.5-4v1": "I_O2.5-4",
  "Illumina HumanOmni2.5-8v1.2": "I_O2.5-8",
  "Illumina HumanOmni2.5Exome-8v1": "I_O2.5E-8v1",
  "Illumina HumanOmni2.5Exome-8v1.1": "I_O2.5E-8v1.1",
  "Illumina HumanOmni2.5Exome-8v1.2": "I_O2.5E-8v1.2",
  "Illumina HumanOmni2.5S-8v1": "I_O2.5S-8v1",
  "Illumina HumanOmni5-4v1": "I_O5-4",
  "Illumina HumanOmni5Exome-4v1": "I_O5E-4",
  "Illumina HumanOmniExpress-12v1": "I_OE-12",
  "Illumina HumanOmniExpress-12v1 FFPE": "I_OE-12f",
  "Illumina HumanOmniExpress-24v1": "I_OE-24",
  "Illumina HumanOmniExpressExome-8v1": "I_OEE-8v1",
  "Illumina HumanOmniExpressExome-8v1.1": "I_OEE-8v1.1",
  "Illumina HumanOmniExpressExome-8v1.2": "I_OEE-8v1.2",
  "Illumina HumanOmniExpressExome-8v1.3": "I_OEE-8v1.3",
  "Illumina HumanOmniZhongHua-8v1": "I_OZH-8v1",
  "Illumina HumanOmniZhongHua-8v1.1": "I_OZH-8v1.1",
  "Illumina HumanOmniZhongHua-8v1.2": "I_OZH-8v1.2",
  "Illumina Infinium OncoArray-500K": "I_OncoArray",
  "Illumina Infinium PsychArray-24v1": "I_Psyc-24v1",
  "Illumina Infinium PsychArray-24v1.1": "I_Psyc-24v1.1"
};

export const CODE_TO_PLATFORM: Record<string, string> = Object.fromEntries(
  Object.entries(PLATFORM_LOOKUP).map(([full, short]) => [short, full])
);
