data:
  snp_dir: '/local/content/analysistools/public_html/apps/LDlink/data/SQLite/snp151/dbsnp.rs.151.db'
  # snp_chr_dir: '/local/content/ldlink/data/snp151/dbsnp.chr.151.db'
  dbsnp_version: '151'
  pop_dir: '/local/content/analysistools/public_html/apps/LDlink/data/1000G/Phase3/samples/'
  vcf_dir: '/local/content/analysistools/public_html/apps/LDlink/data/1000G/Phase3/genotypes/ALL.chr'
  reg_dir: '/local/content/analysistools/public_html/apps/LDlink/data/SQLite/regulomedb/regulomedb.db'
  gene_dir: '/local/content/analysistools/public_html/apps/LDlink/data/SQLite/refGene/sorted_refGene.txt.gz'
  gene_c_dir: '/local/content/analysistools/public_html/apps/LDlink/data/SQLite/refGene/sorted_refGene_collapsed.txt.gz'
  gene_dir2: '/local/content/analysistools/public_html/apps/LDlink/data/SQLite/refGene/gene_names_coords.db'
  recomb_dir: '/local/content/analysistools/public_html/apps/LDlink/data/recomb/genetic_map_autosomes_combined_b37.txt.gz'
