env: 'local'
data:
  dbsnp_version: '155'
  data_dir: '<ABSOLUTE_PATH_TO_DATA_DIR>'
  tmp_dir: '<ABSOLUTE_PATH_TO_TMP_DIR>'
  log_dir: '<ABSOLUTE_PATH_TO_LOG_DIR>'
  ldassoc_example_dir: 'ldassoc_example/'
  population_samples_dir: '1000G_population_samples/'
  genotypes_dir: '1000G/'
  recomb_dir: 'recomb/'
  ldtrait_src: 'https://www.ebi.ac.uk/gwas/api/search/downloads/alternative'
api:
  require_token: True
  restrict_concurrency: True
  # specify mongodb instance where api user records and logs are located, if env is local then use as endpoint for all mongodb calls
  api_mongo_addr: '<MONGODB_ENDPOINT_ADDRESS>'
  # token_experation_days only applies if token_expiration is True
  token_expiration: False
  token_expiration_days: 365
  email_account: '<EMAIL_HOST_SERVER_ADDRESS>'
  api_superuser: '<YOUR_EMAIL_ADDRESS>'
database:
  mongo_user_readonly: '<USERNAME_READ_ONLY>'
  mongo_user_api: '<USERNAME_READ_WRITE>'
  mongo_password: '<PASSWORD>'
  mongo_port: 27017
performance:
  # specify number of parallel processes to use in some modules
  num_subprocesses: 4
aws:
  bucket: <S3_BUCKET_NAME>
  data_subfolder: 'ldlink'
  # use AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for local development only, otherwise leave empty string
  aws_access_key_id: <AWS_ACCESS_KEY_ID>
  aws_secret_access_key: <AWS_SECRET_ACCESS_KEY>
